import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { CartProvider } from "@/contexts/CartContext";
import { Navbar } from "@/components/navbar";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className}`}
      >
        <CartProvider>
        <Navbar />
        {children}
        </CartProvider>
          
      </body>
    </html>
  );
}
